version: '3.7'
services:
## Hume Core Services
  neo4j:
    image: neo4j:4.2.5-enterprise
    ports:
      - "${NEO4J_HTTP_PORT:-7474}:7474"
      - "${NEO4J_BOLT_PORT:-7687}:7687"
    environment:
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_AUTH=neo4j/${NEO4J_PASSWORD:-password}
      - NEO4J_dbms_memory_heap_maxSize=4G
      - NEO4J_dbms_connector_bolt_advertised__address=${HUME_ADVERTISED_ADDRESS:-localhost}:${NEO4J_PORT:-7687}
      - NEO4JLABS_PLUGINS=["apoc","graph-data-science"]
    volumes:
      - "hume_neo4j_data:/data"
      - "hume_neo4j_plugins:/plugins"
  orchestra:
    image: docker.graphaware.com/public/hume-orchestra:${HUME_VERSION}
    ports:
      - 8100:8100
    volumes:
      - ${HUME_PUBLIC_DIR:-./public}:/data
  postgres:
    image: postgres:12.0
    environment:
      POSTGRES_PASSWORD: ${HUME_DB_PASSWORD:-pgsqls3cr3t}
      POSTGRES_USER: ${HUME_DB_USER:-hume}
    ports:
      - 5432:5432
    volumes:
      - "hume_postgres_data:/var/lib/postgresql/data"
  api:
    image: docker.graphaware.com/public/hume-api:${HUME_VERSION}
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/${HUME_DB_USER:-hume}
      - SPRING_DATASOURCE_USERNAME=${HUME_DB_USER:-hume}
      - SPRING_DATASOURCE_PASSWORD=${HUME_DB_PASSWORD:-pgsqls3cr3t}
      - hume.orchestra.uri=http://orchestra:8100
      - hume.orchestra.experimental.enabled=${HUME_EXPERIMENTAL_ENABLED:-false}
      - HUME_BLOBSTORE_ADAPTER=minio
      - HUME_BLOBSTORE_ADAPTER_S3_IDENTITY=${BLOBSTORE_ACCESS_KEY}
      - HUME_BLOBSTORE_ADAPTER_S3_CREDENTIAL=${BLOBSTORE_SECRET_KEY}
      - HUME_BLOBSTORE_ADAPTER_S3_HOST=http://blobstore:9000
      - HUME_BLOBSTORE_CONTAINER=hume-bucket
  web:
    image: docker.graphaware.com/public/hume-web:${HUME_VERSION}
    environment:
      - HUME_API_URL=http://${HUME_ADVERTISED_ADDRESS:-localhost}:${HUME_API_PORT:-8080}
    ports:
      - "${HUME_FRONT_PORT:-8081}:80"
# Ecosystem Services : Blobstore, Entity Extraction, Textrank, PDF Parser
  blobstore:
    image: docker.graphaware.com/public/hume-blobstorage:${HUME_VERSION}
    restart: always
    environment:
      - MINIO_ACCESS_KEY=${BLOBSTORE_ACCESS_KEY}
      - MINIO_SECRET_KEY=${BLOBSTORE_SECRET_KEY}
    volumes:
      - "hume_blobstore_data:/data"
    command: "server /data"
    ports:
      - 9000:9000
  annotation-service:
    image: docker.graphaware.com/public/hume-annotation-service:${HUME_VERSION}
    environment:
      - SERVER_PORT=8085
      - server.tomcat.max-connections=2
      - "JAVA_OPTS=-Xmx4g"
      - hume.config.store.driver=blobstore
      - HUME_CONFIG_STORE_HOST=http://blobstore:9000
      - HUME_CONFIG_STORE_ACCESS_KEY=${BLOBSTORE_ACCESS_KEY}
      - HUME_CONFIG_STORE_ACCESS_SECRET=${BLOBSTORE_SECRET_KEY}
    ports:
      - 8085:8085
  textrank-service:
    image: docker.graphaware.com/public/hume-textrank-service:${HUME_VERSION}
    environment:
      - server.port=8086
    ports:
      - 8086:8086
  tikapdf:
    image: docker.graphaware.com/public/hume-tika-pdf:${HUME_VERSION}
    ports:
      - "8089:8089"
volumes:
  hume_postgres_data:
  hume_neo4j_data:
  hume_neo4j_plugins:
  hume_blobstore_data:
